name: Latest blog post workflow
on:
  # schedule: # Run workflow automatically
    #- cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in FloresBenavides.com posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://floresbenavides.com/feed/?cuac=zero"

  update-readme-with-news:
    name: Update this repo's README with latest news from media
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in tech feeds
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/tag/javascript,http://lifehacker.com/index.xml,https://www.thecrazyprogrammer.com/feed"
          feed_names: "Dev.to/JS,Lifehacker,Crazy Programmer"
          max_post_count: "40"
          comment_tag_name: "TECH-POSTS"
          template: "$newline- [$feedName] [$title]($url)"
